### PR TITLE
Bugfix: Invalid OMIM refs showing up in output

### PR DESCRIPTION
**Pull request by joeflack4**
### Updates
```
Misc
    - Update: parse_morbid_map(): Added currently unused `phenotype_mapping_key_meanings` with a comment explaining how to use it.

    Misc
    - Update: Comments
    - Update: Minor refactoring
```

### Addresses
https://github.com/monarch-initiative/mondo-ingest/issues/98

### CODE REVIEW

**Comment by joeflack4** [comment]
## Analysis results
Will explain more in [the issue](https://github.com/monarch-initiative/mondo-ingest/issues/98), but here are some preliminary output from analysis which we can look over to investigate further: 
[confusingMimNums.csv](https://github.com/monarch-initiative/omim/files/9740439/confusingMimNums.csv)

**Comment by joeflack4** [comment]
This will be ready to merge if we determine that nothing needs to be done. It contains some minor refactors / misc updates. But likely we will need to update/fix something. Just not clear exactly what that will be yet.

**Review by matentzn — APPROVED** [review]

**Comment by matentzn** [comment]
No problem with the changes here, feel free to merge but don't close related issue yet.

**Comment by joeflack4** [comment]
Sounds good. Will merge this and keep issue open.

**Pull request merged**
